require(COVID19)
require(ggplot2)
require(dplyr)
require(countrycode)
require(ISOcodes)
require(stringr)
require(stringi)
require(stringdist)
library(effects)
library(lmPerm)
library(earlyR)
library(EpiEstim)
library(tidyr)
library(abind)
library(reshape2)

# per mappe...
require(maps)
require(rnaturalearth)
require(rnaturalearthdata)
require(psych)
# librerie
source("Michele/lib/long2wide.R") 
source("Michele/lib/merger.R")
#source("Michele/lib/policies.R") 
source("Michele/lib/lagdata.R") 
source("Angela/Compute_R0.R")
source("Angela/merge_dat_R0.R")
source("Angela/compute_R0_ML.R")
